import: models.projection_pramp:ProjectionPRampModel
init:
  sigma0: 0.3
  max_gen: 80000
  seed: 42
  restarts: 10
  scheduler:
    import: frameopt.model.p_scheduler:AdaptivePScheduler
    init:
      p0: 4.0
      p_max: 1.0e+12
      window: 100
  energy:
    import: frameopt.core.energy:mellowmax_coherence