import: models.tr:TRModel
init:
  maxiter: 15000
  seed: 42
  restarts: 10
  energy:
    import: frameopt.core.energy:mellowmax_coherence
    kwargs:
      omega: 20
  grad:
    import: frameopt.core.energy:grad_mellowmax_coherence
    kwargs:
      omega: 20